### ISSUE TITLE
Vertical Metrics: add numerical information

### ISSUE THREAD

**Issue by m4rc1e** [m4rc1e/gfregression#10]
It would be useful to see the numerical information regarding vertical metric values as well.

**Comment by davelab6** [comment]
> Right now, I’m not sure if I’m actually exporting a 200-unit lineGap value instead of 90, but my files don’t indicate this. Regardless, it would be great to see the baselines or something similar. Not sure how doable this is, but that would make the feature more directly useful.

**Comment by m4rc1e** [comment]
Added in https://github.com/m4rc1e/gfregression/commit/69e293810893773c7a3b5e9a85bffd2a7041baac

Closing
