### ISSUE TITLE
html2canvas integration

### ISSUE THREAD

**Issue by davelab6** [m4rc1e/gfregression#11]
https://github.com/niklasvh/html2canvas could be integrated to make it easy to generate a GIF for inclusion in a deck/pdf 

Details in https://stackoverflow.com/questions/4912092/using-html5-canvas-javascript-to-take-screenshots/6678156#6678156

**Comment by m4rc1e** [comment]
@davelab6 thanks! this looks pretty cool. I'll see if it handles gifs :-)

**Comment by m4rc1e** [comment]
I would prefer to handle this on the server side using Selenium, http://www.idiotinside.com/2015/10/20/take-screenshot-selenium-python/ using phantomJS as the driver.

**Comment by m4rc1e** [comment]
This is now handled by [diffbrowsers](https://github.com/googlefonts/diffbrowsers) which uses the Browserstack api. This allows us to test on diff browsers/platforms as well.
