### ISSUE TITLE
Hangs indefinitely when uploading 2 local fonts

### ISSUE THREAD

**Issue by madig** [m4rc1e/gfregression#15]
"Comparing two sets of local fonts" on http://45.55.138.144/, dragging in two fonts and clicking upload makes the site hang...

**Comment by m4rc1e** [comment]
Alright found the issue with Dejavu

```
fonts_after = models.add_fonts(after, 'after', uuid)
  File "/Users/marc/Documents/gfregression/app/models.py", line 39, in add_fonts
    fonts.append(add_font(path, font_type, uuid))
  File "/Users/marc/Documents/gfregression/app/models.py", line 47, in add_font
    family_name, style = filename[:-4].split('-')
```

The filename didn't follow the pattern I was expecting which is FamilyName-StyleName.ttf. For Dejavu, the filename is DejaVuSans.ttf. 

At GF, font filenames must mention the style. For everyone else this isn't a deal breaker so I'll modify this now.

In the meantime, if you're curious to have a look around, rename your font to DejaVuSans-Regular.ttf

I will also include better error handling so when tracebacks occur, you'll see errors on a dedicated page.
