### ISSUE TITLE
Comparing two fonts: unintuitive drop zone order

### ISSUE THREAD

**Issue by madig** [m4rc1e/gfregression#18]
I assumed the first drop zone is the "before" font and the second the "after" font. It's actually switched.

Maybe make the drop zones horizontal and name them explicitly, like:
```
[ Before ] => [ After ]
```

**Comment by m4rc1e** [comment]
@madig thanks, I'll take a look.

btw, I'm rebuilding the docker image so it will be down for 30 mins or so. Sorry for the inconvenience. I need to work on getting a better deployment setup running using Docker.

If you're in need of getting this run locally, I'm more than happy to have a google hangout.

**Comment by madig** [comment]
Thanks for the offer, still experimenting -- will notify you when I need help :)

**Comment by m4rc1e** [comment]
Current solution


![screen shot 2018-04-04 at 11 41 52](https://user-images.githubusercontent.com/7525512/38303203-3bb878ba-37fd-11e8-9780-7fd9b295b1c0.png)

**Comment by madig** [comment]
That'll do for now :)
