### ISSUE TITLE
Less destructive deployment

### ISSUE THREAD

**Issue by m4rc1e** [m4rc1e/gfregression#24]
This app runs on a tiny Digital Ocean droplet. Because of this constraint the DB and app are inside the same container. This is bad because if we rebuild the container, we lose all the data.

Since We have a few open prs in fonts/google which must remain intact. I cannot rebuild the containers just yet. Once the prs have been merged. I'll work on giving the db its own container. This means we can rebuild the webapp without destroying any existing comparisons.

cc @davelab6 @madig

**Comment by m4rc1e** [comment]
Using docker for deployment was simple (pre database days). During the flight to Berlin, I'll see if using  http://flask.pocoo.org/docs/0.12/patterns/fabric/ is easier for individuals to spin their own instance. My original intention for this app was KISS. I avoided using front end frameworks so perhaps dropping Docker should alsomake things easier.

**Comment by madig** [comment]
Maybe an easy way to start it locally with the option to put it in a container? Would also help with development.

**Comment by madig** [comment]
Why a database, anyway?

**Comment by m4rc1e** [comment]
> Why a database, anyway?

When I make pull requests. Reviewers can inspect the changes themselves. Here's one for FrancoisOne https://github.com/google/fonts/pull/1475

**Comment by davelab6** [comment]
We need to throw away your DO container anyway and move it to GCP.

**Comment by davelab6** [comment]
This repo need to move to /googlefonts org ASAP:)
