### ISSUE TITLE
Compare against 2nd dropped family

### ISSUE THREAD

**Issue by davelab6** [m4rc1e/gfregression#7]
It is useful to compare not only against a same-named family in GF API, but also against a 2nd dropped family.

**Comment by m4rc1e** [comment]
Agreed. This is definitely feasible and will expand its usage quite a bit.

**Comment by m4rc1e** [comment]
Now implemented :-)

https://github.com/m4rc1e/gfregression/commit/e838f12f3f359b8e674c33b70b5f27c4592dc49b

![gf-compare-2](https://user-images.githubusercontent.com/7525512/28012680-805075bc-655e-11e7-9008-8401f188d50a.gif)

**Comment by davelab6** [comment]
Well done!!

On Jul 10, 2017 5:57 AM, "Marc Foley" <notifications@github.com> wrote:

Now implemented :-)

e838f12
<https://github.com/m4rc1e/gfregression/commit/e838f12f3f359b8e674c33b70b5f27c4592dc49b>

[image: gf-compare-2]
<https://user-images.githubusercontent.com/7525512/28012680-805075bc-655e-11e7-9008-8401f188d50a.gif>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/m4rc1e/gfregression/issues/7#issuecomment-314060810>,
or mute the thread
